"""empty message

Revision ID: 7d65c94fdf68
Revises: 
Create Date: 2021-12-02 16:25:59.588847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d65c94fdf68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('entrypagename', sa.VARCHAR(length=35), nullable=True),
    sa.Column('rolecode', sa.INTEGER(), nullable=False),
    sa.Column('roledesc', sa.VARCHAR(length=35), nullable=True),
    sa.Column('roleshortdesc', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('rolecode'),
    sa.UniqueConstraint('roleshortdesc')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('emailaddress', sa.VARCHAR(length=50), nullable=True),
    sa.Column('password', sa.VARCHAR(length=22), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('reg_complete', sa.BOOLEAN(), nullable=True),
    sa.Column('authenticated', sa.BOOLEAN(), nullable=True),
    sa.Column('anonymous', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('lastlogin', sa.TIMESTAMP(), nullable=True),
    sa.Column('preferredname', sa.VARCHAR(length=16), nullable=True),
    sa.Column('title', sa.CHAR(length=3), nullable=True),
    sa.Column('firstname', sa.VARCHAR(length=14), nullable=True),
    sa.Column('mi', sa.CHAR(length=1), nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=16), nullable=True),
    sa.Column('namesuffix', sa.CHAR(length=3), nullable=True),
    sa.Column('fs_uniquifier', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fs_uniquifier')
    )
    op.create_table('userrole',
    sa.Column('emailaddress', sa.VARCHAR(length=50), nullable=True),
    sa.Column('rolecode', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['emailaddress'], ['user.emailaddress'], ),
    sa.ForeignKeyConstraint(['rolecode'], ['role.rolecode'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userrole')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
